# Generated by Django 4.2.11 on 2024-04-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images/products', verbose_name='تصویر محصول'),
        ),
    ]
