# Generated by Django 4.2.11 on 2024-04-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=200, verbose_name='دامنه سایت')),
                ('address', models.CharField(max_length=200, verbose_name=']درس سایت')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن سایت')),
                ('fax', models.CharField(blank=True, max_length=200, null=True, verbose_name='فکس سایت')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='ایمیل سایت')),
                ('copy_right', models.TextField(max_length=200, verbose_name='متن کپی رایت سایت')),
                ('about_us_text', models.TextField(max_length=200, verbose_name='متن درباره ما سایت')),
                ('site_logo', models.ImageField(max_length=200, upload_to='', verbose_name='لوگو سایت')),
                ('is_main_setting', models.BooleanField(max_length=200, verbose_name='تنظیمات اصلی سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
