# Generated by Django 4.2.11 on 2024-04-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_footerlinkbox_alter_sitesetting_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.CharField(max_length=200, verbose_name='لینک')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان لینک')),
                ('description', models.TextField(max_length=200, verbose_name='توضیحات اسلایدر')),
                ('image', models.ImageField(max_length=200, upload_to='', verbose_name='تصویر اسلایدر')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
        migrations.AlterModelOptions(
            name='footerlink',
            options={'verbose_name': 'لینک  فوتر', 'verbose_name_plural': ' لینک های فوتر'},
        ),
        migrations.AlterModelOptions(
            name='footerlinkbox',
            options={'verbose_name': 'دسته بندی لینک فوتر', 'verbose_name_plural': 'دسته بندی لینک های فوتر'},
        ),
    ]
