# Generated by Django 4.2.11 on 2024-04-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='موضوع مقاله')),
                ('url_title', models.CharField(max_length=200, verbose_name='لینک مقاله')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/ غیر فعال')),
            ],
            options={
                'verbose_name': 'دسته بندی مقاله',
                'verbose_name_plural': 'دسته بندی های مقاله',
            },
        ),
    ]
