# Generated by Django 4.2.11 on 2024-04-24 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0006_remove_articlecategory_author_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 4, 24), verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
