# Generated by Django 4.2.11 on 2024-04-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0008_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله', 'verbose_name_plural': 'نظرات مقاله'},
        ),
    ]
