# Generated by Django 4.2.11 on 2024-04-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن همراه'),
        ),
    ]
