# Generated by Django 4.2.11 on 2024-04-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_user',
            field=models.TextField(null=True, verbose_name='درباره شخص'),
        ),
    ]
